### PR TITLE
Fix sink pad ordering

### LINKED ISSUE #210: Cannot receive webrtc streams from Servo
When testing this please use https://github.com/servo/media/pull/208 . The bug is present without those changes, but is harder to test since the sink code is broken too.

For testing we're using the signalling server in https://github.com/jdm/gstwebrtc-demos/tree/nossl : `python -m SimpleHTTPServer` in the `js` folder, and `./simple-server.py` in the `signalling` folder. You'll need to remove the data channel code from webrtc.js

Currently we have three webrtc clients:

 - Firefox or any other browser, using its own webrtc implementation, pointed at `localhost:8000`
 - Servo, using servo-medias webrtc implementation, pointed at `localhost:8000` (with `dom.webrtc.enabled` set in prefs.json)
 - The simple_webrtc client, which emulates the javascript running on `localhost:8000`, and can be run against itself (`cargo ex simple_webrtc 8443` and then `cargo ex simple_webrtc 8443 <peer id>`)

With https://github.com/servo/media/pull/208 applied, running `simple_webrtc` against `simple_webrtc` works fine, as does running Firefox against `simple_webrtc`.

Servo does not. The servo side does not yet implement _playing_ streams, so we can expect that to not work, however it does support creating streams and sending them over webrtc, using the same servo-media code that simple_webrtc uses. When you run servo against simple_webrtc:

 - the negotiation runs fine
 - servo does indeed see the streams from simple_webrtc (as a pad-added signal)
 - simple_webrtc does _not_ receive the pad-added signal for servo's streams

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #210

Based on #208

This implements a version of the fix detailed in https://github.com/servo/media/issues/210#issuecomment-467365523

Instead of unlinking/relinking, we simply keep new streams unlinked until we decide to trigger an offer, at which point we link them to new request pads. The answerer side keeps them unlinked until it gets a remote offer, at which point it also requests pads and links them to the correctly numbered request pads.

A missing piece was that the payload number also has to match, so we keep track of that too.

r? @jdm @slomo (last two commits only)

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm done for the day, but I do need to write some more comments for this. Will do tomorrow.

File: backends/gstreamer/src/webrtc.rs [hunk 1]
```diff
@@ -146,14 +177,128 @@ impl GStreamerWebRtcController {
...
+                for _ in self.request_pad_counter..=idx {
+                    // webrtcbin needs you to request pads (or use element.link(webrtcbin))
+                    // however, it also wants them to be connected in the correct order.
+                    //
+                    // Here, we make sure all the numbered sink pads have been created beforehand, up to
+                    // and including the one we need here.
+                    //
+                    // An alternate fix is to sort pending_streams according to the m-line index
+                    // and just do it in order. This also seems brittle.
+                    webrtc.get_request_pad("sink_%u").unwrap();
```
Comment (Manishearth) [inline backends/gstreamer/src/webrtc.rs]: I feel like there's an underlying bug here, this should be unnecessary

cc @slomo

File: webrtc/src/thread.rs [hunk 2]
```diff
@@ -90,6 +90,7 @@ pub enum InternalEvent {
     OnNegotiationNeeded,
     OnIceCandidate(IceCandidate),
     OnAddStream(Box<MediaStream>),
+    DescriptionAdded(SendBoxFnOnce<'static, ()>, bool, SdpType),
```
Comment (jdm) [inline webrtc/src/thread.rs]: Maybe use an enum instead of a bool here?

File: backends/gstreamer/src/webrtc.rs [hunk 3]
```diff
@@ -146,14 +194,128 @@ impl GStreamerWebRtcController {
...
+        let caps = stream.caps();
+        let webrtc = self.webrtc.as_ref().unwrap();
+        let idx = self.remote_mline_info.iter().enumerate()
+            .filter(|(_, x)| !x.is_used)
+            .find(|(_, x)| x.caps.can_intersect(&caps))
+            .map(|x| x.0);
+        let element = stream.src_element();
+
+        if let Some(idx) = idx {
+            if idx >= self.request_pad_counter {
```
Comment (jdm) [inline backends/gstreamer/src/webrtc.rs]: Is there any risk that we could call link_stream with !request_new_pads but end up running this code that requests pads? Would that be bad? I find the logic here a little bit obtuse.

Comment (Manishearth) [reply backends/gstreamer/src/webrtc.rs]: Yes, this code requesting new pads is fine, `request_new_pads` is about requesting new pads when there is no remote m-line: in that case we normally want to just buffer it up for later, except for when we're making an offer, at which point we want to flush all buffered streams.

The behavior of this function with `!request_new_pads` is "request pads only if they have been set up by the remote already", which is too long to fit in a variable. I can document this more explicitly.

**Comment by slomo** [comment]
@Manishearth You are mentioning the wrong guy in your PR.

**Comment by Manishearth** [comment]
Oh, sorry about that!
